/* Main.c file generated by New Project wizard
 *
 * Created:   Пт июн 6 2025
 * Processor: 80C31
 * Compiler:  SDCC for 8051
 */
 
#include <mcs51reg.h>
#include <stdint.h>
#include <8051.h>
#include <math.h>
#include <stdio.h>

#define RL1 P3_5 
#define RL2 P3_6 
#define RL3 P3_7  

char buffer[50];

const unsigned char segment_codes[] = {
    0x3F, // 0
    0x06, // 1
    0x5B, // 2
    0x4F, // 3
    0x66, // 4
    0x6D, // 5
    0x7D, // 6
    0x07, // 7
    0x7F, // 8
    0x6F  // 9
};
 
 void delay_t(uint32_t ms){
	for (uint32_t i = 0; i < ms; i++)
	   {
	      for (int j = 0; j < 85; j++);
	   }
}

void UART_Init() {
    TMOD = 0x20;
    TH1 = 0xFD;
    SCON = 0x50;
    TR1 = 1;
   TL1=0xFD;
}


unsigned char UART_Receive(unsigned int timeout) {
    while (timeout--) {
        if (RI) {
            RI = 0;
            return SBUF;
        }
        for (int i = 0; i < 85; i++);
    }
    return '*';
}

void putc(uint8_t input){
	SBUF = input;
	while (TI != 1){}
	TI = 0;
}

void send_string(const char *str) {
    while (*str) {
        putc(*str++);
    }
}

void display_digit_color(unsigned char digit, char color) {
    RL1 = 0;
    RL2 = 0;
    RL3 = 0;

    if (color == 'r') RL3 = 1;     // red
    else if (color == 'b') RL1 = 1; // blue
    else if (color == 'g') RL2 = 1; // green

    P0 = 0xFF-segment_codes[digit];
}

void set_number(unsigned char d1,  unsigned char d2, unsigned char d3, int it, int delay)
{
   if (!(d1 >= '0' && d1 <= '9' && d2 >= '0' && d2 <= '9' && d3 >='0' && d3 <= '9'))
   {
	 return;
   }
     RL1 = 0;
     RL2 = 0;
      RL3 = 0;
      for (int i = 0; i < it; i++)
      {
	 P0 = 0xFF-segment_codes[d1-'0'];
	 RL1 = 1;
	 delay_t(delay);
	 RL1 =0;
	 P0 = 0xFF-segment_codes[d2-'0'];
	 RL2 = 1;
	 delay_t(delay);
	 RL2=0;
	 P0 = 0xFF-segment_codes[d3-'0'];
	 RL3 = 1;
	 delay_t(delay);
	 RL3=0;
      }
}

void main(void)
 { 
    
    RL1 = 0;
    RL2 = 0;
    RL3 = 0;
    P2=2;
    delay_t(100);
    P2=3;
    UART_Init();
    
    unsigned int cnt = 0;
    unsigned char d1 = '0', d2 = '0', d3 = '0';
    unsigned char d1_new = '0', d2_new = '0';
    
    const unsigned int DELAY = 500;
    const unsigned int IT = 1;
    unsigned int time_passed = 0;
   while (1)
   {
      if (time_passed >= 1000)
      {
	 sprintf(buffer, "%.d#", P1);
	 send_string(buffer);
	 time_passed = 0;
      }
      if (RI)
      {
	    unsigned char inp = UART_Receive(100);
	    if (inp > '9' || inp < '0')
	    {
		  cnt = 0;
	       }
	       else
	       {
		     cnt += 1;
		     if (cnt == 1)
		     {
			   d1_new = inp;
			}
		     else if (cnt == 2)
		     {
			   d2_new = inp;
			}
		     else if (cnt >= 3)
		     {
			   d1 = d1_new;
			   d2 = d2_new;
			   d3 = inp;
			   cnt = 0;
			}
		  }
	 }
      set_number(d1, d2, d3, IT, DELAY);
      time_passed += IT * DELAY * 3;
   }
 }